OnlineJudgeOrg/OnlineJudgeOrg

javaTest/src/ShSeanLee/BOJ2587_Median.java

test_sh 1st commit

---

javaTest/src/ShSeanLee/BOJ2587_Median.java

test_sh2 1st commit

---

javaTest/src/javaTest/bj_1436.java

test3 song

---

javaTest/src/javaTest/bj_1436.java

git test4 sh

---

javaTest/src/ShSeanLee/BOJ10815_NumberCard.java
javaTest/src/ShSeanLee/BOJ10989_SortingNumbers3.java
javaTest/src/ShSeanLee/BOJ1427_SortInside.java
javaTest/src/ShSeanLee/BOJ25035_Cutline.java
javaTest/src/ShSeanLee/BOJ2751_SortingNumbers2.java

11/13 5 BOJ codes updated

---

javaTest/src/ShSeanLee/BOJ10815_NumberCard.java
javaTest/src/ShSeanLee/BOJ11650_SortingCoordinates.java
javaTest/src/ShSeanLee/BOJ11651_SortingCoordinates2.java
javaTest/src/ShSeanLee/BOJ1181_SortingWords.java
javaTest/src/ShSeanLee/BOJ14425_StringSets.java
javaTest/src/ShSeanLee/BOJ2751_SortingNumbers2.java
javaTest/src/ShSeanLee/BOJ7785_IsInCompany.java

11/19 5 BOJ codes updated(Week4)
[정렬] 좌표정렬하기, 좌표정렬하기2, 단어정렬하기
[집합과 맵] 문자열 집합, 회사에 있는 사람

11/19 5 BOJ codes updated(Week4)

---

javaTest/src/ShSeanLee/BOJ11650_SortingCoordinates.java
javaTest/src/ShSeanLee/BOJ11651_SortingCoordinates2.java
javaTest/src/ShSeanLee/BOJ1181_SortingWords.java
javaTest/src/ShSeanLee/BOJ14425_StringSets.java
javaTest/src/ShSeanLee/BOJ7785_IsInCompany.java

11/21 5 BOJ codes' annotation updated(Week4)

11/21 5 BOJ codes' annotation updated(Week4)

---

javaTest/src/ShSeanLee/BOJ11650_SortingCoordinates.java

11-22 Annotation Added

---

javaTest/src/ShSeanLee/BOJ10814_OrderByAge.java

11-23 Updated

---

javaTest/src/ShSeanLee/BOJ10814_OrderByAge.java

11-24 BOJ10814_OrderByAge Updated

11-24 BOJ10814_OrderByAge Updated

---

javaTest/src/ShSeanLee/BOJ10816_NumberCards2.java
javaTest/src/ShSeanLee/BOJ1620_Pocketmon.java
javaTest/src/ShSeanLee/BOJ1764_Unknown.java
javaTest/src/ShSeanLee/BOJ18870_CoordinateCompression.java

11-25 4 solution Updated

---

javaTest/src/ShSeanLee/BOJ10814_OrderByAge.java
javaTest/src/ShSeanLee/BOJ10816_NumberCards2.java
javaTest/src/ShSeanLee/BOJ1620_Pocketmon.java
javaTest/src/ShSeanLee/BOJ1764_Unknown.java
javaTest/src/ShSeanLee/BOJ18870_CoordinateCompression.java

11-28 week 5 Annotation Added

---

javaTest/src/ShSeanLee/BOJ11478_DifferentString.java
javaTest/src/ShSeanLee/BOJ1269_SymmetricDifference.java
javaTest/src/ShSeanLee/BOJ13241_LeastCommonMultiple.java
javaTest/src/ShSeanLee/BOJ1735_IrreducibleFraction.java
javaTest/src/ShSeanLee/BOJ1934_LeastCommonMultiple.java

- Solved 5 problems.
- 5 files updated.

Update 5 solutions Week 6

---

javaTest/src/ShSeanLee/BOJ11478_DifferentString.java
javaTest/src/ShSeanLee/BOJ1269_SymmetricDifference.java
javaTest/src/ShSeanLee/BOJ13241_LeastCommonMultiple.java
javaTest/src/ShSeanLee/BOJ1735_IrreducibleFraction.java
javaTest/src/ShSeanLee/BOJ1934_LeastCommonMultiple.java

- Annotation added in detail.
- BOJ1934 TreeSet speed test added.

Update 5 Annotation Week 6

---

javaTest/src/ShSeanLee/Math2/BOJ1929_GetPrime.java
javaTest/src/ShSeanLee/Math2/BOJ4948_Bertrand_postulate.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ12789_GetSnacks.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ18258_Queue2.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ4949_Balanced.java

- math 2 (2 solutions), SQD (3 soultions)

Upload Week 8 files

---

javaTest/src/ShSeanLee/Math2/BOJ1929_GetPrime.java
javaTest/src/ShSeanLee/Math2/BOJ4948_BertrandPostulate.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ12789_GetSnacks.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ4949_Balanced.java

Week 8 Annotation Added

---

javaTest/src/ShSeanLee/Math2/BOJ13909_ClosingWindows.java
javaTest/src/ShSeanLee/Math2/BOJ17103_GoldBachPartition.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ11866_Josephus0.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ2164_Card2.java

Week 9 3/5 Solved

---

javaTest/src/ShSeanLee/Math2/BOJ13909_ClosingWindows.java

Week 9 5/5 Solved

---

javaTest/src/ShSeanLee/Math2/BOJ13909_ClosingWindows.java
javaTest/src/ShSeanLee/Math2/BOJ17103_GoldBachPartition.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ11866_Josephus0.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ2164_Card2.java
javaTest/src/ShSeanLee/Stack_Queue_Deque/BOJ28279_Deque2.java

Week 9 Solved

---

javaTest/src/ShSeanLee/Backtracking/BOJ15649_NAndM.java
javaTest/src/ShSeanLee/Backtracking/BOJ15650_NAndM2.java
javaTest/src/ShSeanLee/Backtracking/BOJ15651_NAndM3.java
javaTest/src/ShSeanLee/Backtracking/BOJ15652_NAndM4.java
javaTest/src/javaTest/GraphTraversal/BOJ24479_DFS1.java

Week 10 Solved (4/5)

---

javaTest/src/javaTest/GraphTraversal/BOJ24479_DFS1.java

Week 10 Solved (5/5)

---

javaTest/src/ShSeanLee/Backtracking/BOJ14888_ArithmeticOperator.java

Week 11 Solved (2/2)

---

javaTest/src/ShSeanLee/GraphTraversal/BOJ24445_BFS2.java
javaTest/src/ShSeanLee/GraphTraversal/BOJ2606_Virus.java

Week 13 Solved (2/2)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ24416_Fibonacci1.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ9184_ExecuteFunction.java
javaTest/src/ShSeanLee/GraphTraversal/BOJ2606_Virus.java

- Modify Week 13 Virus
- 1/5 solved
- Revise 2/5

Week 14 Solved (1/5)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1904_01Tile.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ9184_ExecuteFunction.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ9461_PadovanSequence.java
javaTest/src/ShSeanLee/GraphTraversal/BOJ1260_DFS_BFS.java

Week 14 Solved (5/5)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1912_SumInARow.java

Week 15 Solved (0/4)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1149_RGBStreet.java

- SumInARow Solving
- Solve RGBStreet

Week 15 Solved (2/4)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1149_RGBStreet.java

Week 15 Solved (4/4)

---

javaTest/src/ShSeanLee/GraphTraversal/BOJ1012_Cabbage.java

Week 16 Solved (0/3)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1463_MakingOne.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ2579_Stairs.java
javaTest/src/ShSeanLee/GraphTraversal/BOJ1012_Cabbage.java

Week 16 Solved (1/3)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ1463_MakingOne.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ2579_Stairs.java

Week 16 Solved (3/3)

---

javaTest/src/ShSeanLee/DynamicProgramming/BOJ10844_StairNumberEZ.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ10844_StairNumberEZ_v2.java
javaTest/src/ShSeanLee/DynamicProgramming/BOJ2156_WineTasting.java

Week 17 Solved (1/3)
